### ISSUE TITLE
Using Expo on Android, ask permissions?

### ISSUE THREAD

**Issue by marchingband** [dotintent/react-native-ble-plx#1001]
I am using EXPO, with the eas build plugin.
On iOS, the app requests permissions when it first opens.
On Android it does not ask permissions, users must manually give permissions from their device settings, both for Location and Bluetooth.
Is there a way to make Android ask for permissions like it does on iOS?
Thank you!!

**Comment by josmas** [comment]
You can use PermissionsAndroid directly from RN https://reactnative.dev/docs/0.68/permissionsandroid or a community package such as https://www.npmjs.com/package/react-native-permissions

**Comment by marchingband** [comment]
In EXPO I believe the plugin is responsible for asking permissions. Do the maintainers of this repo also maintain the expo plugin?

**Comment by benjaminhera** [comment]
This behaviour is giving me a headache, because it instantly shows up the permission modal, which interferes with my splash screen on ios and makes my app unusable... On android I use PermissionsAndroid from react to do the logic manually.

Please have the option to disable automatic permission requesting for ios. Thanks.

**Comment by marchingband** [comment]
@benjaminhera I think that is the native behavior, not something that can be controlled on iOS.
