### ISSUE TITLE
🐛 Android crashes on bluetooth device disconnect 

### ISSUE THREAD

**Issue by bj97301** [dotintent/react-native-ble-plx#1103]
### Prerequisites

- [X] I checked the documentation and FAQ without finding a solution
- [X] I checked to make sure that this issue has not already been filed

### Expected Behavior

shouldnt crash

### Current Behavior

crashes

### Library version

3.0.0

### Device

pixle 7a

### Environment info

```shell
see screenshot
```

### Steps to reproduce

1. connect to device
2. disconnect(i just shut down the power on the Bluetooth device)
3. crashes
env info:
![Screenshot 2023-10-03 at 11 23 52 AM](https://github.com/dotintent/react-native-ble-plx/assets/1450431/038b8df2-31cb-4ea7-936c-08c32c8c6c27)

crash:
![Screenshot 2023-10-03 at 11 24 23 AM](https://github.com/dotintent/react-native-ble-plx/assets/1450431/21c770c1-74b2-4443-b4fb-22bc91b0a995)

### Formatted code sample or link to a repository

```js
sorry let me know if you really need that but I think the stack trace should be good nuff right?
```

### Relevant log output

```shell
see screenshots
```

**Comment by bj97301** [comment]
Let me know if you need anything else.  Love the package.  Keep up the amazing work 🤘

**Comment by andycamp** [comment]
We are also getting this exception after upgrading to 3.0.0. Thanks.

**Comment by contactsimonwilson** [comment]
I'm also facing the same issue

**Comment by eliaslecomte** [comment]
I'm having a similar crash but just on connect, after something like 10 seconds 🤔.

**Comment by lucaswitch** [comment]
I can confirm that it's happening on 3.0.0 on Android 12 just like @eliaslecomte says after 5~6 seconds after monitor.

**Comment by lucaswitch** [comment]
The solution is downgrade to latest version before 3.0.0 on Android.

**Comment by lucaswitch** [comment]
Here is the repro.
Happening when monitor characteristics at same time. (Don't know if it's related).
```js
// Monitor
device.monitorCharacteristicForService(
      'some service id',
      'some characteristic id',
      handleOnCharacteristicChanged
)

device.monitorCharacteristicForService(
      'some service id',
      'some other characteristic id',
      handleOnCharacteristicChanged
)
// the after some  moments seconds the crash happens.
```
Here is the full stack trace of the error?
![Screenshot_2023-10-06-18-19-43-221_com miui bugreport](https://github.com/dotintent/react-native-ble-plx/assets/29023475/9de3c3a5-f2dd-4f4b-9159-b207066e5729)

**Comment by bj97301** [comment]
> Here is the repro. Happening when monitor characteristics at same time. (Don't know if it's related).
> 
> ```js
> // Monitor
> device.monitorCharacteristicForService(
>       'some service id',
>       'some characteristic id',
>       handleOnCharacteristicChanged
> )
> 
> device.monitorCharacteristicForService(
>       'some service id',
>       'some other characteristic id',
>       handleOnCharacteristicChanged
> )
> // the after some  moments seconds the crash happens.
> ```
> 
> Here is the full stack trace of the error? ![Screenshot_2023-10-06-18-19-43-221_com miui bugreport](https://user-images.githubusercontent.com/29023475/273334709-9de3c3a5-f2dd-4f4b-9159-b207066e5729.jpg)


Interesting. I’ll see if it doesn’t happen to me if I don’t monitor shits.

**Comment by lucaswitch** [comment]
Seems to be a problem with the RXJava:

On Android side we use the [RxAndroidBle](https://github.com/Polidea/RxAndroidBle) library of Polidea. After migration towards RxJava 2 some of the errors are not routed properly to their listeners and thus this will result in a BLE Undeliverable Exception. The root cause lies in the threading of the Android OS. As workaround RxJava has a hook where you can set the global errorhandler. For more info see [RxJava docs](https://github.com/ReactiveX/RxJava/wiki/What's-different-in-2.0#error-handling) .

A default workaround implementation in the Flutter app (needs to be in the Java / Kotlin part e.g. mainactivity) is shown below. For an example (in Java) see Polidea RxAndroidBle [sample](https://github.com/Polidea/RxAndroidBle/tree/master/sample/src/main/java/com/polidea/rxandroidble2/sample).

BleException is coming from Polidea RxAndroidBle, so make sure your application declares the following depedency: implementation "com.polidea.rxandroidble2:rxandroidble:1.11.1"

RxJavaPlugins.setErrorHandler { throwable ->
  if (throwable is UndeliverableException && throwable.cause is BleException) {
    return@setErrorHandler // ignore BleExceptions since we do not have subscriber
  }
  else {
    throw throwable
  }
}

**Comment by bj97301** [comment]
@dominik-czupryna-withintent Any thoughts on this one?  I am hoping to test out your 3.0.0 package but this is blocking me at the moment.

**Comment by dominik-czupryna-withintent** [comment]
Currently, we have this error reproduced and described, waiting for fix. We plan to release a fix this or next week.

**Comment by lucaswitch** [comment]
Apparently is caused by RxJava, the events need to have always a subscriber or it will lead to undeliverable exception crashes.

**Comment by eliaslecomte** [comment]
So it now no longer crashes with the 3.1.0 release but I am loosing connection after 4/5 seconds on Android.

**Comment by simonitfi** [comment]
Also it seems onDisconnected is not called on Android. https://github.com/dotintent/react-native-ble-plx/issues/1126

**Comment by andycamp** [comment]
Confirming that onDisconnect is not called on android.

**Comment by eliaslecomte** [comment]
Should this be reopened or should I report a new issue?
